### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by MonirMooghen** [TobiasBarbosa/ProjectCalculationTool#11]

**Comment by Vahablotfi** [comment]
Mht. databasen bør I beskrive overvejelser i jeres design, f.eks.
•Tabellerderikke er på 3. normal form, herunderforklare hvorfor det er gjort (tidspres eller anden overvejelse)
•Tabeller der ikke benytterautomatisk genereretID som nøgle
•Valg af fremmednøgler, constraints, unik indeks, osv.
